### ISSUE TITLE
where i can found the database schema file ?

### ISSUE THREAD

**Issue by kacedali** [QoboLtd/project-template-cakephp#272]

**Comment by mamchenkov** [comment]
Hi,

the database is setup using the [CakePHP Migrations](https://book.cakephp.org/3.0/en/migrations.html).  You can find the migration files in `config/Migrations` folder.  If you need to work with a database dump (**not recommended**), then you can place it in `etc/mysql.sql`).

**Comment by kacedali** [comment]
hi
its possible to load main menu from the database table ?
the only solution i found is to load from menu,json file

**Comment by mamchenkov** [comment]
Hi,

yes, it is possible.  Navigate to `menu/menus/` and you should see two menus - one for admin and one for main.  If you edit the menu and unset the 'Default' flag, then you'll be able to edit the menu structure via the web interface and it will be stored in the database.
