### ISSUE TITLE
problem when executing composer exec -- phake app:install

### ISSUE THREAD

**Issue by kacedali** [QoboLtd/project-template-cakephp#308]
hi, problem when installing application
```
composer exec -- phake app:install
Welcome to phake-builder!
Use "phake -T" to list all commands.
More info at https://github.com/QoboLtd/phake-builder
----------------------------------------------------------------------
[2017-08-09 10:49:08] :INFO : Task: builder:init (Initialize builder configuration)
----------------------------------------------------------------------
[2017-08-09 10:49:08] :INFO : Task: dotenv:create (Create .env file)
[2017-08-09 10:49:08] :OK   : SUCCESS! Generated
----------------------------------------------------------------------
[2017-08-09 10:49:08] :INFO : Task: dotenv:reload (Reload settings from .env file)
[2017-08-09 10:49:08] :OK   : SUCCESS!
----------------------------------------------------------------------
[2017-08-09 10:49:08] :INFO : Task: file:process (Processing template file)
[2017-08-09 10:49:08] :OK   : SUCCESS! Processed 2799 bytes.
----------------------------------------------------------------------
[2017-08-09 10:49:08] :INFO : Task: mysql:database-create (Create database)

aborted!
[2017-08-09 10:49:08] :ERROR: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-paie' at line 1

(See full trace by running task with --trace)
```

**Comment by mamchenkov** [comment]
@kacedali the default installation assumes that:

* You are connection to a locally installed MySQL server (`DB_HOST=localhost`)
* The database name for your application is specified either in the `.env` file (`DB_NAME=my_app`) or via the command line argument to `app:install` as per README: `composer exec -- phake app:install DB_NAME=YOUR_DATABASE_NAME`.
* The database does not yet exist in your MySQL server.
* Administrative functions can be performed by user `root` without any password.  (`DB_ADMIN_USER` and `DB_ADMIN_PASS`).

If any of the above settings are different for your setup, you need to either adjust your `.env` file and run the `app:install` again, or pass the parameters to the `app:install` which will get preference from those in the `.env` file.

Can you please check the above and let me know if you still experience the issue.

Thanks!

**Comment by kacedali** [comment]
its done after changing the name of database from db-app to dbapp !!!
thanks for your fast replay :)

**Comment by mamchenkov** [comment]
@kacedali glad it worked for you.

As a side note, I don't think MySQL allows dashes in the database/table names.  So that's why `db-app` didn't work.  But if you want to use a separator, then an underscore should be just fine (`db_app`).
