### ISSUE TITLE
Searchable fields for table [Cars] cannot be empty.

### ISSUE THREAD

**Issue by kacedali** [QoboLtd/project-template-cakephp#313]
hi @mamchenkov 
how to work with this plugin ? or where to define searchable fields ?

**Comment by mamchenkov** [comment]
hi @kacedali ,

this is coming from the [cakephp-search](https://github.com/QoboLtd/cakephp-search/) plugin of ours. We need to update the documentation for it, especially after a recent major release. But this will take us some time.

For now, try to do one of the following.  Either provide the basic search fields configuration by adding `basic_search_fields=brand,model,year` (adjust as needed) to the `config/Modules/Cars/config/config.ini` file in the `[table]` section.

Or you can create the index view for your module.  Simply drop the following:

```
FIELD NAME
model
brand
year
```
into `config/Modules/Cars/views/index.csv` file.

This should fix the issue you are having now, but I'm pretty sure you'll find a variety of the new ones.

If at any moment you want to give up on search, simply mark the module as non-searchable, by adding `searchable=false` to the `[table]` section of the `config.ini` of your module.

Please let me know how it goes. :smile:

**Comment by kacedali** [comment]
hi @mamchenkov again :)
I tried both solutions but it does not work :/

i still have same problem :
Searchable fields for table [Cars] cannot be empty.

⟩ Search\Model\Table\SavedSearchesTable->_getBasicSearchFields
ROOT\vendor\qobo\cakephp-search\src\Model\Table\SavedSearchesTable.php, line 604

i will try this tomorrow again

thanks.

**Comment by mamchenkov** [comment]
@kacedali we just realized that this is caused by a bug, which is a leftover piece of code from a recent refactoring.  We should have an update with the fix early next week (Monday-Tuesday).

Sorry about that.

**Comment by mamchenkov** [comment]
Hi @kacedali ,

we have released a new major version today.  Can you please try to upgrade and let me know if the issue is resolved.

Thanks!

**Comment by kacedali** [comment]
hi @mamchenkov 
same problem :(

Searchable fields for table [Countries] cannot be empty.
InvalidArgumentException

⟩ Search\Model\Table\SavedSearchesTable->_getBasicSearchFields
ROOT\vendor\qobo\cakephp-search\src\Model\Table\SavedSearchesTable.php, line 606
⟩ Search\Model\Table\SavedSearchesTable->_getBasicSearchCriteria
ROOT\vendor\qobo\cakephp-search\src\Model\Table\SavedSearchesTable.php, line 552
⟩ Search\Model\Table\SavedSearchesTable->prepareData
ROOT\vendor\qobo\cakephp-search\src\Controller\SearchTrait.php, line 48
⟩ App\Controller\AppController->search
CORE\src\Controller\Controller.php, line 440
⟩ Cake\Controller\Controller->invokeAction
CORE\src\Http\ActionDispatcher.php, line 119
⟩ Cake\Http\ActionDispatcher->_invoke
CORE\src\Http\ActionDispatcher.php, line 93
⟩ Cake\Http\ActionDispatcher->dispatch
CORE\src\Routing\Dispatcher.php, line 60
⟩ Cake\Routing\Dispatcher->dispatch
ROOT\webroot\index.php, line 37

**Comment by mamchenkov** [comment]
hi @kacedali ,

this fix turned out to be very slippery - it escaped from us not once, but twice.  I think we have finally managed to catch and merge it in.  Please update to [cakephp-search v13.0.2](https://github.com/QoboLtd/cakephp-search/releases/tag/v13.0.2).

**Comment by kacedali** [comment]
hi @mamchenkov,

fixed but empty result
I send you more details
- the result screenshot :
![qobo](https://user-images.githubusercontent.com/26823221/29610039-ebdfa924-87f0-11e7-84da-ed8ac8811ad7.jpg)
- the saved search content from database :
{"saved":{"criteria":[],"aggregator":"OR","display_columns":[],"sort_by_field":"Countries.nom_en_gb","sort_by_order":"desc"},"latest":{"criteria":[],"aggregator":"OR","display_columns":[],"sort_by_field":"Countries.nom_en_gb","sort_by_order":"desc"}}
- the config.ini
[table]
basic_search_fields = code,alpha2,alpha3,nom_en_gb,nom_fr_fr

i go try to do some debug to find the problem

**Comment by mamchenkov** [comment]
@kacedali thanks for the update!

I am working on the fix now as well.  The search apparently works sometimes, but only for the admin user (full access).  For users without full access, a different error is thrown.

Stay tuned for the update. :)

**Comment by mamchenkov** [comment]
Hi @kacedali ,

we just tagged [cakephp-search v13.0.3](https://github.com/QoboLtd/cakephp-search/releases/tag/v13.0.3).  Can you please try with this version and let me know if the issue is resolved.

Thanks a lot for your feedback!

**Comment by mamchenkov** [comment]
@kacedali ,

before you were searching in module 'Cars', no?  Can you try that same module as you saw the problem originally.  That one should work.

For the 'Users' module, we are bringing the dataTables search instead of the main search in the left panel.  See the PR #332 .

**Comment by mamchenkov** [comment]
Hi @kacedali ,

we just released the following two versions:

* [project-template-cakephp v31.1.1](https://github.com/QoboLtd/project-template-cakephp/releases/tag/v31.1.1)
* [cakephp-search v13.0.4](https://github.com/QoboLtd/cakephp-search/releases/tag/v13.0.4)

These are fixing some issues with search, AJAX, and the way we load the AdminLTE theme.  Please give it a spin and let me know if it finally works for you. :)

Thanks!

**Comment by kacedali** [comment]
hi @mamchenkov ,
still no working but maybe the broblem because i use xampp !!!

**Comment by mamchenkov** [comment]
hi @kacedali ,

hmm ... then I need more information.  What is the error you are currently getting?

**Comment by mamchenkov** [comment]
@kacedali did you manage to make it work or do you still have a problem and just gave up? :)

**Comment by kacedali** [comment]
hi @mamchenkov 
its done, work perfect
thanks :)

**Comment by mamchenkov** [comment]
@kacedali thanks for letting me know!  Good luck with your project.
